### ISSUE TITLE
gremlin-http fails with following error when assigned same instance id as being in use previously

### ISSUE THREAD

**Issue by miteshvp** [fabric8-analytics/gremlin-docker#4]
```
Caused by: com.thinkaurelius.titan.core.TitanException: A Titan graph with the same instance id [0a8102e51-bayesian-gremlin-http-1-xsjni1] is already open. Might required forced shutdown.
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:146)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:94)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:74)
... 13 more
```

We have seen this issue happening very rarely. Root cause of the problem is two Titan graphs with the same instance id does not work. It happens very rarely, and also, out of our scope to fix it to happening.

Issue Upstream - https://github.com/awslabs/dynamodb-titan-storage-backend/issues/198

**Comment by miteshvp** [comment]
Resolution : - Restart gremlin-http pod so that it takes a different name should pretty much solve the problem

**Comment by fridex** [comment]
So does it mean that we will have to do manual restarts?

**Comment by miteshvp** [comment]
Yes, that's correct. Unless we have a handle on restarting the pod with a different name. I don't know if that's possible

**Comment by vpavlin** [comment]
There is no way this is a resolution of the problem. This is an ugly workaround and temporary fix:)

**Comment by fridex** [comment]
> There is no way this is a resolution of the problem. This is an ugly workaround and temporary fix:)

+1 :)

**Comment by miteshvp** [comment]
Feel free to fix it.

**Comment by miteshvp** [comment]
Have opened a conversation here - https://github.com/awslabs/dynamodb-titan-storage-backend/issues/198

**Comment by msrb** [comment]
Just FYI: https://stackoverflow.com/questions/33632710/cant-connect-to-titandb-a-titan-graph-with-the-same-instance-id-is-already

**Comment by vpavlin** [comment]
It would be interesting to know what is really happening and what is causing this issue - because it says "Titan graph already exists", but Titan is part of the gremlin image so if gremlin dies, Titan dies, unless Titan keeps some runtime metadata somewhere else - DynamoDB.

The link @msrb sent could be useful if we would be able able to get management system of titan before we properly start gremlin and thus be able to force close the instance and then finish the gremlin startup. But I don't know if that is doable. 

Something for you, @miteshvp, to look at;)

**Comment by miteshvp** [comment]
Yes, thanks Michal, looked into that link already.

**Comment by miteshvp** [comment]
+1 @vpavlin

**Comment by vpavlin** [comment]
See http://s3.thinkaurelius.com/docs/titan/0.5.0/titan-config-ref.html#_graph

`graph.unique-instance-id`

This should give us some flexibility so we can for example set it to a random UUID instead of let titan to generate it as our instance id will be same across restarts - hostname does not change, process id is also the same as there only one process running.

Just to raise priority of this issue - any random restart of the container (node restart, OOM kill, liveness probe failure...) will cause a restart of the pod which will then trigger this issue.

**Comment by miteshvp** [comment]
This looks promising. Let me look into this. Thanks @vpavlin

**Comment by miteshvp** [comment]
@vpavlin @msrb https://github.com/fabric8-analytics/gremlin-docker/pull/5

**Comment by miteshvp** [comment]
Fixed in https://github.com/fabric8-analytics/gremlin-docker/pull/5
